version: 2
updates:
  - package-ecosystem: npm
    directory: /
    labels:
      - dependencies
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
