name: 'Playwright report comment'
description: 'Report Playwright test results as pull request comments'
author: 'Philipp Daun <daun@daun.ltd>'

branding:
  icon: 'message-circle'
  color: 'purple'

inputs:
  github-token:
    description: 'The GitHub access token'
    required: false
    default: ${{ github.token }}
  report-file:
    description: 'Path to the generated json report file'
    required: true
  report-tag:
    description: 'Tag reports to distinguish test runs in the same workflow instead of overwriting'
    required: false
  report-url:
    description: 'URL to the generated html report, if uploaded'
    required: false
  pr-number:
    description: 'The pull request number to comment on. Only required if the action is run outside a pull request context.'
    required: false
  create-comment:
    description: 'Create a pull request comment with the test result summary'
    required: false
    default: 'true'
  comment-title:
    description: 'Customize the title of the pull request comment'
    required: false
    default: 'Playwright test results'
  custom-info:
    description: 'Additional information to include in the summary comment, markdown-formatted'
    required: false
  job-summary:
    description: 'Create a job summary comment for the workflow run'
    required: false
    default: 'false'
  icon-style:
    description: 'The icons to use: octicons or emoji'
    required: false
    default: 'octicons'
  test-command:
    description: 'The command used to run the tests'
    required: false
  footer:
    description: 'Additional content to add to the comment below the test report'
    required: false
    default: ''

outputs:
  summary:
    description: 'The rendered markdown summary of the test report'
  comment-id:
    description: 'The ID of the comment that was created or updated'
  report-data:
    description: 'The raw data of the test report'

runs:
  using: node20
  main: dist/index.js
